### PR TITLE
CA-281950: Failed to create VDI if SR free space is too low

### PR DESCRIPTION
**Pull request by DeliZhangX**
Signed-off-by: Deli Zhang <Deli.Zhang@citrix.com>

### CODE REVIEW

**Comment by DeliZhangX** [comment]
Hi @rdobson,
Sorry to bother you again, would you mind adding me in XenCert maintainer group.
@vivekkumac had transferred the maintain-ship to me, but until now I just begin to work on it.

Thanks :)

**Comment by vivekkumac** [comment]
Hi Chandrika,  Gary,

Can you help Deli in gaining maintainer permissions for XenCert in Github.

Regards,
Vivek

**Comment by rdobson** [comment]
Deli - I've added you.

**Comment by DeliZhangX** [comment]
appreciate @rdobson

**Comment by DeliZhangX** [comment]
Thank for your help as well @vivekkumac

**Comment by minli1** [comment]
LGTM.

**Pull request merged**
