### PR TITLE
Updating guide for Citrix Hypervisor 8.0

### PR DESCRIPTION
**Pull request by thomasmck**
Signed-off-by: Thomas Mckelvey <thomas.mckelvey@citrix.com>

### CODE REVIEW

**Comment by DeliZhangX** [comment]
one "XenServer" needs to change to "Citrix Hypervisor"
Other is LGTM

**Comment by chandrikas** [comment]
LGTMT 👍

**Comment by thomasmck** [comment]
Removed the XenServer reference.

**Comment by thomasmck** [comment]
Can't seem to get the merge conflict to resolve properly. @DeliZhangX are you ok with me force pushing directly to master? (after making a backup branch)

**Comment by DeliZhangX** [comment]
Just go ahead

**Pull request closed without merging**
