### PR TITLE
Updated XenCert Docs for XS 7.1

### PR DESCRIPTION
**Pull request by vivekkumac**
XenCert is v3.0
Docs are Updated with versions
Docs are having better formatting and readability

### CODE REVIEW

**Comment by chandrikas** [comment]
Changes look good @vivekkumac. However, I notice that the Guide is full of mixed font. I appreciate that some of it was already there but could we please take this opportunity to correct it?

**Comment by chandrikas** [comment]
The installation instructions in the guide say

> xe update-upload file-name=”/root/ xencert-supp-pack.iso” \<it will return update uuid of xencert package on successful upload\> 
> xe update-apply uuid=\<update uuid of ACK\> host=\<host uuid\>

- There should be no space between root and iso name in "file-name"
- In the second command, uuid should be update uuid of xencert

**Comment by chandrikas** [comment]
Thanks @vivekkumac. Please squash your commits and I'll merge it to the master repo.

**Comment by vivekkumac** [comment]
@chandrikas commits are squashed with a better commit message. Please merge.

Thanks,
Vivek

**Pull request closed without merging**
