### PR TITLE
CA-293886: Remove the limitation that total time of disk IO test.

### PR DESCRIPTION
**Pull request by lln133208**
As titled.

Passed job id: 2273363

Signed-off-by: Yuan Ren <yuan.ren@citrix.com>

### CODE REVIEW

**Comment by lln133208** [comment]
@thomasmck  This is corresponding changes in xencert with removing limitation of estimated time from Xenrt code.

**Comment by thomasmck** [comment]
@lln133208 I get that this will allow the tests the pass but it will still take a really long time for large LUNs. Could we update the test so that it just writes to everyother block or a portion of the LUN or somthing like that to make it faster?

**Comment by DeliZhangX** [comment]
> @lln133208 I get that this will allow the tests the pass but it will still take a really long time for large LUNs. Could we update the test so that it just writes to everyother block or a portion of the LUN or somthing like that to make it faster?

@thomasmck I create new task CP-29861 to track

**Comment by MarkSymsCtx** [comment]
@deliz I think the test has already been updated to only write to 50G anyway?

**Comment by DeliZhangX** [comment]
I checked code quickly and did not see such 50G limit. Also I am running FCoE testing for driver update and found LUN partitions are written entirely without any limit.
The test spends so long time is caused by not only size, but also write method, as I saw 
```
lseek(fd, i * DEFAULT_SECTOR_SIZE, SEEK_SET)
```
is called for each sector that indicates huge IO will require to LUN to decline write speed.

So we need to investigate further and give better test policy.

**Pull request merged**
